// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Contributors: typeof import('./theme/components/Contributors.vue')['default']
    Demo: typeof import('./theme/components/Demo.vue')['default']
    Example: typeof import('./theme/components/demo/Example.vue')['default']
    Link: typeof import('./theme/components/Link.vue')['default']
    SourceCode: typeof import('./theme/components/demo/SourceCode.vue')['default']
    VpExample: typeof import('./theme/components/demo/vp-example.vue')['default']
    VpSourceCode: typeof import('./theme/components/demo/vp-source-code.vue')['default']
  }
}
